### ISSUE TITLE
checkpoint 1 is ready for review

### ISSUE THREAD

**Issue by erickr19** [erickr19/scent-dex#1]
@pawaitemadisoncollege checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Hi @erickr19! You have a good start here with your screens and user stories. I'm excited about this project because its very unique compared to what others have built in previous semesters!

**User Stories**

Great use of Trello!  Your MVP stories seem to be well-scoped for a semester of work.  

- [ ] One requirement for the project is full CRUD (create/read/update/delete).  I think only the delete scenario is missing the MVP - is there something meaningful that you could add that would involve deleting? If not, we can discuss other ways for you to demonstrate that proficiency. 

- [ ] Have you considered which web service or api you might use in your project? 

**Time log/journal** 

I appreciate the thought that you are putting into documenting what you accomplished each week. Taking the time to think about what you are doing/learning and how you are feeling can really help you be successful in anything you do!

**Project plan**

- [ ] Have you started planning out the individual tasks for each story? This could also be done in Trello, or a page in your repo like this: https://github.com/mad-ent-java-s23/FatBikeTrailReports/blob/main/ProjectPlan.md.

**Questions**

- [ ] Do you have plans for how data will be added into the system? Is this something you'll repopulate directly in the database or could that be pulled in from one or more apis?
